[package]
name = "soro_gps"
version = "0.1.0"
edition = "2021"


[lib]
crate-time = ["staticlib"]

[features]
default = ["python"]
python = ["pyo3"]

[dependencies]
pisserror = "0.3.0-rc.2"
tracing = "0.1.41"
pyo3 = { version = "0.23.4", optional = true, features = ["extension-module"] }

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.10"

## python build configuration
[tool.maturin]
bindings = "pyo3"
features = ["python"]

[dev-dependencies]
tracing-subscriber = "0.3.19"
